### ISSUE TITLE
video upload -> find idols -

### ISSUE THREAD

**Issue by SunnyBaik** [swsnu/swpp2021-team7#103]
커서가 포인터로 뜨는데 인터랙션이 없어서요, 버튼이 아니라면 빼는게 좋을 것 같습니다.

**Comment by iks15174** [comment]
의견 감사합니다. 인터랙션이 없는 부분은 커서가 포인터로 뜨지 않도록 수정하겠습니다

**Comment by eunbin1227** [comment]
#107 말씀해주신 부분 수정 완료했습니다. 의견 감사합니다!
