### ISSUE TITLE
Video Clip 생성 기능

### ISSUE THREAD

**Issue by 9ummy** [swsnu/swpp2021-team7#104]
기능과 직접적으로 관련이 있는 피드백은 아니지만
비디오 클립 생성 기능이 서비스에서 중요한 기능인 듯한데 메인 페이지에서 좀 더 부각되어도 좋을 것 같습니다!

**Comment by iks15174** [comment]
좋은 의견 감사합니다!

**Comment by eunbin1227** [comment]
#107 말씀해주신 부분 수정 완료했습니다. 의견 감사합니다!
