### ISSUE TITLE
비로그인 상태시 Hottest Idol 로딩

### ISSUE THREAD

**Issue by SunnyBaik** [swsnu/swpp2021-team7#98]
로그인하지 않으면 Hottest Idols가 로딩이 되지 않는데 따로 이유가 있을까요? 로딩 중인지 알고 좀 기다렸는데 로그인 하니까 바로 뜨네요. 따로 이유가 없다면 바로 뜨는 편이 좋을 것 같습니다.

**Comment by iks15174** [comment]
좋은 의견 감사합니다. 로그인 안 해도 확인 할 수 있도록 고치겠습니다

**Comment by eunbin1227** [comment]
#107 말씀해주신 부분 수정 완료했습니다. 의견 감사합니다!
